<?php
// $Id$

/**
 * @file
 * Defines a field type for referencing a game clock.
 */

/**
 * Implementation of hook_menu().
 */
function game_clock_field_menu() {
  $items = array();
  $items['game_clock_field/autocomplete'] = array(
    'title' => 'Game clock field autocomplete',
    'page callback' => 'game_clock_field_autocomplete',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );
  return $items;
}

/**
 * Implementation of hook_theme().
 */
function game_clock_field_theme() {
  return array(
    'game_clock_field_select' => array(
      'arguments' => array('element' => NULL),
    ),
    'game_clock_field_buttons' => array(
      'arguments' => array('element' => NULL),
    ),
    'game_clock_field_autocomplete' => array(
      'arguments' => array('element' => NULL),
    ),
    'game_clock_field_formatter_default' => array(
      'arguments' => array('element'),
    ),
    'game_clock_field_formatter_admin' => array(
      'arguments' => array('element'),
    ),
    'game_clock_field_formatter_title' => array(
      'arguments' => array('element'),
      'function' => 'theme_game_clock_field_formatter_column',
    ),
    'game_clock_field_formatter_turn' => array(
      'arguments' => array('element'),
      'function' => 'theme_game_clock_field_formatter_column',
    ),
    'game_clock_field_formatter_type' => array(
      'arguments' => array('element'),
      'function' => 'theme_game_clock_field_formatter_column',
    ),
    'game_clock_field_formatter_status' => array(
      'arguments' => array('element'),
      'function' => 'theme_game_clock_field_formatter_column',
    ),
    'game_clock_field_formatter_increment' => array(
      'arguments' => array('element'),
      'function' => 'theme_game_clock_field_formatter_column',
    ),
    'game_clock_field_formatter_next_tick' => array(
      'arguments' => array('element'),
      'function' => 'theme_game_clock_field_formatter_column',
    ),
    'game_clock_field_formatter_init' => array(
      'arguments' => array('element'),
      'function' => 'theme_game_clock_field_formatter_column',
    ),
    'game_clock_field_formatter_cid' => array(
      'arguments' => array('element'),
      'function' => 'theme_game_clock_field_formatter_column',
    ),
  );
}

/**
 * Implementation of hook_field_info().
 */
function game_clock_field_field_info() {
  return array(
    'game_clock_field' => array(
      'label' => t('Game clock'),
      'description' => t('Store the ID of a game clock as an integer value.'),
    ),
  );
}

/**
 * Implementation of hook_field_settings().
 */
function game_clock_field_field_settings($op, $field) {
  switch ($op) {
    case 'form':
      module_load_include('inc', 'game_clock', 'includes/game_clock.admin');
      $form = array();
      $form['referenceable_types'] = array(
        '#type' => 'checkboxes',
        '#title' => t('Game clock types that can be referenced'),
        '#multiple' => TRUE,
        '#default_value' => is_array($field['referenceable_types']) ? $field['referenceable_types'] : array(),
        '#options' => array_map('check_plain', _game_clock_types()),
      );
      if (module_exists('views')) {
        $views = array('--' => '--');
        $all_views = views_get_all_views();
        foreach ($all_views as $view) {
          // Only 'game_clock' views that have fields will work for our purpose.
          if ($view->base_table == 'game_clock' && !empty($view->display['default']->display_options['fields'])) {
            if ($view->type == 'Default') {
              $views[t('Default Views')][$view->name] = $view->name;
            }
            else {
              $views[t('Existing Views')][$view->name] = $view->name;
            }
          }
        }

        if (count($views) > 1) {
          $form['advanced'] = array(
             '#type' => 'fieldset',
             '#title' => t('Advanced - Game clocks that can be referenced (View)'),
             '#collapsible' => TRUE,
             '#collapsed' => !isset($field['advanced_view']) || $field['advanced_view'] == '--',
           );
          $form['advanced']['advanced_view'] = array(
            '#type' => 'select',
            '#title' => t('View used to select the game clocks'),
            '#options' => $views,
            '#default_value' => isset($field['advanced_view']) ? $field['advanced_view'] : '--',
            '#description' => t('Choose the "Views module" view that selects the game clocks that can be referenced.<br />Note:<ul><li>Only views that have fields will work for this purpose.</li><li>This will discard the "Game clock types" settings above. Use the view\'s "filters" section instead.</li><li>Use the view\'s "fields" section to display additional informations about candidate game clocks on game clock creation/edition form.</li><li>Use the view\'s "sort criteria" section to determine the order in which candidate game clocks will be displayed.</li></ul>'),
          );
          $form['advanced']['advanced_view_args'] = array(
            '#type' => 'textfield',
            '#title' => t('View arguments'),
            '#default_value' => isset($field['advanced_view_args']) ? $field['advanced_view_args'] : '',
            '#required' => FALSE,
            '#description' => t('Provide a comma separated list of arguments to pass to the view.'),
          );
        }
      }
      return $form;

    case 'save':
      $settings = array('referenceable_types');
      if (module_exists('views')) {
        $settings[] = 'advanced_view';
        $settings[] = 'advanced_view_args';
      }
      return $settings;

    case 'database columns':
      $columns = array(
        'cid' => array('type' => 'int', 'unsigned' => TRUE, 'not null' => FALSE),
      );
      return $columns;

    case 'views data':
      $data = content_views_field_views_data($field);
      $db_info = content_database_info($field);
      $table_alias = content_views_tablename($field);

      // Filter: swap the handler to the 'in' operator.
      $data[$table_alias][$field['field_name'] .'_cid']['filter']['handler'] = 'content_handler_filter_many_to_one';
      // Argument: use game_clock.title for summaries.
      $data[$table_alias][$field['field_name'] .'_cid']['argument']['name table'] = 'game_clock';
      $data[$table_alias][$field['field_name'] .'_cid']['argument']['name field'] = 'title';
      // Relationship: add a relationship for related game clock.
      $data[$table_alias][$field['field_name'] .'_cid']['relationship'] = array(
        'base' => 'game_clock',
        'field' => $db_info['columns']['cid']['column'],
        'handler' => 'content_handler_relationship',
        'label' => t($field['widget']['label']),
        'content_field_name' => $field['field_name'],
      );
      return $data;
  }
}

/**
 * Implementation of hook_field().
 */
function game_clock_field_field($op, &$node, $field, &$items, $teaser, $page) {
  switch ($op) {
    case 'validate':
      // Extract cids to check.
      $ids = array();
      foreach ($items as $delta => $item) {
        if (is_array($item) && !empty($item['cid']) && is_numeric($item['cid'])) {
          $ids[] = $item['cid'];
        }
      }
      $refs = _game_clock_field_potential_references($field, '', NULL, $ids);
      foreach ($items as $delta => $item) {
        if (is_array($item)) {
          $error_element = isset($item['_error_element']) ? $item['_error_element'] : '';
          if (is_array($item) && isset($item['_error_element'])) unset($item['_error_element']);
          if (!empty($item['cid']) && !isset($refs[$item['cid']])) {
            form_set_error($error_element, t("%name: this game clock can't be referenced.", array('%name' => t($field['widget']['label']))));
          }
        }
      }
      return $items;
  }
}

/**
 * Implementation of hook_content_is_empty().
 */
function game_clock_field_content_is_empty($item, $field) {
  if (empty($item['cid'])) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implementation of hook_field_formatter_info().
 */
function game_clock_field_field_formatter_info() {
  return array(
    'default' => array(
      'label' => t('Title (with turn)'),
      'field types' => array('game_clock_field'),
      'multiple values' => CONTENT_HANDLE_CORE,
    ),
    'title' => array(
      'label' => t('Title (no turn)'),
      'field types' => array('game_clock_field'),
      'multiple values' => CONTENT_HANDLE_CORE,
    ),
    'type' => array(
      'label' => t('Type'),
      'field types' => array('game_clock_field'),
      'multiple values' => CONTENT_HANDLE_CORE,
    ),
    'status' => array(
      'label' => t('Status'),
      'field types' => array('game_clock_field'),
      'multiple values' => CONTENT_HANDLE_CORE,
    ),
    'increment' => array(
      'label' => t('Increment'),
      'field types' => array('game_clock_field'),
      'multiple values' => CONTENT_HANDLE_CORE,
    ),
    'next_tick' => array(
      'label' => t('Next tick'),
      'field types' => array('game_clock_field'),
      'multiple values' => CONTENT_HANDLE_CORE,
    ),
    'init' => array(
      'label' => t('Init'),
      'field types' => array('game_clock_field'),
      'multiple values' => CONTENT_HANDLE_CORE,
    ),
    'cid' => array(
      'label' => t('CID'),
      'field types' => array('game_clock_field'),
      'multiple values' => CONTENT_HANDLE_CORE,
    ),
  );
}

/**
 * Theme function for 'default' game_clock_field field formatter.
 */
function theme_game_clock_field_formatter_default($element) {
  $output = '';
  if (!empty($element['#item']['cid']) && is_numeric($element['#item']['cid']) && ($title = _game_clock_field_titles($element['#item']['cid']))) {
    $state = game_clock_state($element['#item']['cid'], TRUE);
    $output = t('%title (@turn)', array('%title' => $state->title, '@turn' => $state->turn));
  }
  return $output;
}

/**
 * Theme function for 'admin' game_clock_field field formatter.
 */
function theme_game_clock_field_formatter_admin($element) {
  $output = '';
  if (!empty($element['#item']['cid']) && is_numeric($element['#item']['cid']) && ($title = _game_clock_field_titles($element['#item']['cid']))) {
    $state = game_clock_state($element['#item']['cid'], TRUE);
    $output = l(t('%title', array('%title' => $state->title)), 'admin/settings/game_clock/'. $state->name);
  }
  return $output;
}

/**
 * Proxy theme function for columns of game_clock_field field formatters.
 */
function theme_game_clock_field_formatter_column($element) {
  $output = '';
  if (!empty($element['#item']['cid']) && is_numeric($element['#item']['cid'])) {
    $state = game_clock_state($element['#item']['cid'], TRUE);
    switch ($element['#formatter']) {
      case 'increment':
        module_load_include('inc', 'game_clock', 'includes/game_clock.admin');
        $output = _game_clock_selections($state->increment);
        break;
      case 'status':
        $output = t('%status', array('%status' => ($state->status ? t('running') : t('paused'))));
        break;
      case 'init':
        $output = t('%init', array('%init' => ($state->init ? t('TRUE') : t('FALSE'))));
        break;
      default:
        $output = check_plain($state->{$element['#formatter']});
        break;
    }
  }
  return $output;
}

/**
 * Helper function for formatters.
 *
 * Store game clock titles collected in the curent request.
 */
function _game_clock_field_titles($cid, $known_title = NULL) {
  static $titles = array();
  if (!isset($titles[$cid])) {
    $title = $known_title ? $known_title : db_result(db_query("SELECT title FROM {game_clocks} WHERE cid=%d", $cid));
    $titles[$cid] = $title ? $title : '';
  }
  return $titles[$cid];
}

/**
 * Implementation of hook_widget_info().
 *
 * We need custom handling of multiple values for the game_clock_field_select
 * widget because we need to combine them into a options list rather
 * than display multiple elements.
 *
 * We will use the content module's default handling for default value.
 *
 * Callbacks can be omitted if default handing is used.
 * They're included here just so this module can be used
 * as an example for custom modules that might do things
 * differently.
 */
function game_clock_field_widget_info() {
  return array(
    'game_clock_field_select' => array(
      'label' => t('Select list'),
      'field types' => array('game_clock_field'),
      'multiple values' => CONTENT_HANDLE_MODULE,
      'callbacks' => array(
        'default value' => CONTENT_CALLBACK_DEFAULT,
      ),
    ),
    'game_clock_field_buttons' => array(
      'label' => t('Check boxes/radio buttons'),
      'field types' => array('game_clock_field'),
      'multiple values' => CONTENT_HANDLE_MODULE,
      'callbacks' => array(
        'default value' => CONTENT_CALLBACK_DEFAULT,
      ),
    ),
    'game_clock_field_autocomplete' => array(
      'label' => t('Autocomplete text field'),
      'field types' => array('game_clock_field'),
      'multiple values' => CONTENT_HANDLE_CORE,
      'callbacks' => array(
        'default value' => CONTENT_CALLBACK_DEFAULT,
      ),
    ),
  );
}

/**
 * Implementation of FAPI hook_elements().
 *
 * Any FAPI callbacks needed for individual widgets can be declared here,
 * and the element will be passed to those callbacks for processing.
 *
 * Drupal will automatically theme the element using a theme with
 * the same name as the hook_elements key.
 *
 * Autocomplete_path is not used by text_widget but other widgets can use it
 * (see game_clock_field and userreference).
 */
function game_clock_field_elements() {
  return array(
    'game_clock_field_select' => array(
      '#input' => TRUE,
      '#columns' => array('uid'), '#delta' => 0,
      '#process' => array('game_clock_field_select_process'),
    ),
    'game_clock_field_buttons' => array(
      '#input' => TRUE,
      '#columns' => array('uid'), '#delta' => 0,
      '#process' => array('game_clock_field_buttons_process'),
    ),
    'game_clock_field_autocomplete' => array(
      '#input' => TRUE,
      '#columns' => array('name'), '#delta' => 0,
      '#process' => array('game_clock_field_autocomplete_process'),
      '#autocomplete_path' => FALSE,
      ),
    );
}

/**
 * Implementation of hook_widget_settings().
 */
function game_clock_field_widget_settings($op, $widget) {
  switch ($op) {
    case 'form':
      $form = array();
      $match = isset($widget['autocomplete_match']) ? $widget['autocomplete_match'] : 'contains';
      if ($widget['type'] == 'game_clock_field_autocomplete') {
        $form['autocomplete_match'] = array(
          '#type' => 'select',
          '#title' => t('Autocomplete matching'),
          '#default_value' => $match,
          '#options' => array(
            'starts_with' => t('Starts with'),
            'contains' => t('Contains'),
          ),
          '#description' => t('Select the method used to collect autocomplete suggestions. Note that <em>Contains</em> can cause performance issues on sites with thousands of nodes.'),
        );
      }
      else {
        $form['autocomplete_match'] = array('#type' => 'hidden', '#value' => $match);
      }
      return $form;

    case 'save':
      return array('autocomplete_match');
  }
}

/**
 * Implementation of hook_widget().
 *
 * Attach a single form element to the form. It will be built out and
 * validated in the callback(s) listed in hook_elements. We build it
 * out in the callbacks rather than here in hook_widget so it can be
 * plugged into any module that can provide it with valid
 * $field information.
 *
 * Content module will set the weight, field name and delta values
 * for each form element. This is a change from earlier CCK versions
 * where the widget managed its own multiple values.
 *
 * If there are multiple values for this field, the content module will
 * call this function as many times as needed.
 *
 * @param $form
 *   the entire form array, $form['#node'] holds node information
 * @param $form_state
 *   the form_state, $form_state['values'][$field['field_name']]
 *   holds the field's form values.
 * @param $field
 *   the field array
 * @param $items
 *   array of default values for this field
 * @param $delta
 *   the order of this item in the array of subelements (0, 1, 2, etc)
 *
 * @return
 *   the form item for a single element for this field
 */
function game_clock_field_widget(&$form, &$form_state, $field, $items, $delta = 0) {
  switch ($field['widget']['type']) {
    case 'game_clock_field_select':
      $element = array(
        '#type' => 'game_clock_field_select',
        '#default_value' => $items,
      );
      break;

    case 'game_clock_field_buttons':
      $element = array(
        '#type' => 'game_clock_field_buttons',
        '#default_value' => $items,
      );
      break;

    case 'game_clock_field_autocomplete':
      $element = array(
        '#type' => 'game_clock_field_autocomplete',
        '#default_value' => isset($items[$delta]) ? $items[$delta] : NULL,
        '#value_callback' => 'game_clock_field_autocomplete_value',
      );
      break;
  }
  return $element;
}

/**
 * Value for a game_clock_field autocomplete element.
 *
 * Substitute in the node title for the node nid.
 */
function game_clock_field_autocomplete_value($element, $edit = FALSE) {
  $field_key  = $element['#columns'][0];
  if (!empty($element['#default_value'][$field_key])) {
    $nid = $element['#default_value'][$field_key];
    $value = db_result(db_query('SELECT c.title FROM {game_clocks} c WHERE c.cid = %d', $cid));
    $value .= ' [cid:'. $cid .']';
    return array($field_key => $value);
  }
  return array($field_key => NULL);
}

/**
 * Process an individual element.
 *
 * Build the form element. When creating a form using FAPI #process,
 * note that $element['#value'] is already set.
 *
 * The $fields array is in $form['#field_info'][$element['#field_name']].
 */
function game_clock_field_select_process($element, $edit, $form_state, $form) {
  // The game_clock_field_select widget doesn't need to create its own
  // element, it can wrap around the optionwidgets_select element.
  // This will create a new, nested instance of the field.
  // Add a validation step where the value can be unwrapped.
  $field_key  = $element['#columns'][0];
  $element[$field_key] = array(
    '#type' => 'optionwidgets_select',
    '#default_value' => isset($element['#value']) ? $element['#value'] : '',
    // The following values were set by the content module and need
    // to be passed down to the nested element.
    '#title' => $element['#title'],
    '#required' => $element['#required'],
    '#description' => $element['#description'],
    '#field_name' => $element['#field_name'],
    '#type_name' => $element['#type_name'],
    '#delta' => $element['#delta'],
    '#columns' => $element['#columns'],
  );
  if (empty($element[$field_key]['#element_validate'])) {
    $element[$field_key]['#element_validate'] = array();
  }
  array_unshift($element[$field_key]['#element_validate'], 'game_clock_field_optionwidgets_validate');
  return $element;
}

/**
 * Process an individual element.
 *
 * Build the form element. When creating a form using FAPI #process,
 * note that $element['#value'] is already set.
 *
 * The $fields array is in $form['#field_info'][$element['#field_name']].
 */
function game_clock_field_buttons_process($element, $edit, $form_state, $form) {
  // The game_clock_field_select widget doesn't need to create its own
  // element, it can wrap around the optionwidgets_select element.
  // This will create a new, nested instance of the field.
  // Add a validation step where the value can be unwrapped.
  $field_key  = $element['#columns'][0];
  $element[$field_key] = array(
    '#type' => 'optionwidgets_buttons',
    '#default_value' => isset($element['#value']) ? $element['#value'] : '',
    // The following values were set by the content module and need
    // to be passed down to the nested element.
    '#title' => $element['#title'],
    '#required' => $element['#required'],
    '#description' => $element['#description'],
    '#field_name' => $element['#field_name'],
    '#type_name' => $element['#type_name'],
    '#delta' => $element['#delta'],
    '#columns' => $element['#columns'],
  );
  if (empty($element[$field_key]['#element_validate'])) {
    $element[$field_key]['#element_validate'] = array();
  }
  array_unshift($element[$field_key]['#element_validate'], 'game_clock_field_optionwidgets_validate');
  return $element;
}

/**
 * Process an individual element.
 *
 * Build the form element. When creating a form using FAPI #process,
 * note that $element['#value'] is already set.
 *
 */
function game_clock_field_autocomplete_process($element, $edit, $form_state, $form) {

  // The game_clock_field autocomplete widget doesn't need to create its own
  // element, it can wrap around the text_textfield element and add an autocomplete
  // path and some extra processing to it.
  // Add a validation step where the value can be unwrapped.
  $field_key  = $element['#columns'][0];

  $element[$field_key] = array(
    '#type' => 'text_textfield',
    '#default_value' => isset($element['#value']) ? $element['#value'] : '',
    '#autocomplete_path' => 'game_clock_field/autocomplete/'. $element['#field_name'],
    // The following values were set by the content module and need
    // to be passed down to the nested element.
    '#title' => $element['#title'],
    '#required' => $element['#required'],
    '#description' => $element['#description'],
    '#field_name' => $element['#field_name'],
    '#type_name' => $element['#type_name'],
    '#delta' => $element['#delta'],
    '#columns' => $element['#columns'],
  );
  if (empty($element[$field_key]['#element_validate'])) {
    $element[$field_key]['#element_validate'] = array();
  }
  array_unshift($element[$field_key]['#element_validate'], 'game_clock_field_autocomplete_validate');

  // Used so that hook_field('validate') knows where to flag an error.
  $element['_error_element'] = array(
    '#type' => 'value',
    // Wrapping the element around a text_textfield element creates a
    // nested element, so the final id will look like 'field-name-0-nid-nid'.
    '#value' => implode('][', array_merge($element['#parents'], array($field_key, $field_key))),
  );
  return $element;
}

/**
 * Validate a select/buttons element.
 *
 * Remove the wrapper layer and set the right element's value.
 * We don't know exactly where this element is, so we drill down
 * through the element until we get to our key.
 *
 * We use $form_state['values'] instead of $element['#value']
 * to be sure we have the most accurate value when other modules
 * like optionwidgets are using #element_validate to alter the value.
 */
function game_clock_field_optionwidgets_validate($element, &$form_state) {
  $field_key  = $element['#columns'][0];

  $value = $form_state['values'];
  $new_parents = array();
  foreach ($element['#parents'] as $parent) {
    $value = $value[$parent];
    // Use === to be sure we get right results if parent is a zero (delta) value.
    if ($parent === $field_key) {
      $element['#parents'] = $new_parents;
      form_set_value($element, $value, $form_state);
      break;
    }
    $new_parents[] = $parent;
  }
}

/**
 * Validate an autocomplete element.
 *
 * Remove the wrapper layer and set the right element's value.
 * This will move the nested value at 'field-name-0-cid-cid'
 * back to its original location, 'field-name-0-cid'.
 */
function game_clock_field_autocomplete_validate($element, &$form_state) {
  $field_name = $element['#field_name'];
  $type_name = $element['#type_name'];
  $field = content_fields($field_name, $type_name);
  $field_key  = $element['#columns'][0];
  $delta = $element['#delta'];
  $value = $element['#value'][$field_key];
  $nid = NULL;
  if (!empty($value)) {
    preg_match('/^(?:\s*|(.*) )?\[\s*cid\s*:\s*(\d+)\s*\]$/', $value, $matches);
    if (!empty($matches)) {
      // Explicit [cid:c].
      list(, $title, $cid) = $matches;
      if (!empty($title) && ($c = game_clock_state($cid, TRUE)) && $title != $c->title) {
        form_error($element[$field_key], t('%name: title mismatch. Please check your selection.', array('%name' => t($field['widget']['label']))));
      }
    }
    else {
      // No explicit cid.
      $reference = _game_clock_field_potential_references($field, $value, 'equals', NULL, 1);
      if (empty($reference)) {
        form_error($element[$field_key], t('%name: found no valid game clock with that title.', array('%name' => t($field['widget']['label']))));
      }
      else {
        // TODO:
        // the best thing would be to present the user with an additional form,
        // allowing the user to choose between valid candidates with the same title
        // ATM, we pick the first matching candidate...
        $cid = key($reference);
      }
    }
  }
  form_set_value($element, $cid, $form_state);
}

/**
 * Implementation of hook_allowed_values().
 */
function game_clock_field_allowed_values($field) {
  $references = _game_clock_field_potential_references($field);

  $options = array();
  foreach ($references as $key => $value) {
    // Views theming runs check_plain (htmlentities) on the values.
    // We reverse that with html_entity_decode.
    $options[$key] = html_entity_decode(strip_tags($value['rendered']), ENT_QUOTES);
  }
  return $options;
}

/**
 * Fetch an array of all candidate referenced nodes.
 *
 * This info is used in various places (aloowed values, autocomplete results,
 * input validation...). Some of them only need the nids, others nid + titles,
 * others yet nid + titles + rendered row (for display in widgets).
 * The array we return contains all the potentially needed information, and lets
 * consumers use the parts they actually need.
 *
 * @param $field
 *   The field description.
 * @param $string
 *   Optional string to filter titles on (used by autocomplete).
 * @param $match
 *   Operator to match filtered name against, can be any of:
 *   'contains', 'equals', 'starts_with'
 * @param $ids
 *   Optional node ids to lookup (the $string and $match arguments will be
 *   ignored).
 * @param $limit
 *   If non-zero, limit the size of the result set.
 *
 * @return
 *   An array of valid nodes in the form:
 *   array(
 *     cid => array(
 *       'title' => The game clock title,
 *       'rendered' => The text to display in widgets (can be HTML)
 *     ),
 *     ...
 *   )
 */
function _game_clock_field_potential_references($field, $string = '', $match = 'contains', $ids = array(), $limit = NULL) {
  static $results = array();

  // Create unique id for static cache.
  $cid = $field['field_name'] .':'. $match .':'. ($string !== '' ? $string : implode('-', $ids)) .':'. $limit;
  if (!isset($results[$cid])) {
    $references = FALSE;
    if (module_exists('views') && !empty($field['advanced_view']) && $field['advanced_view'] != '--') {
      $references = _game_clock_field_potential_references_views($field, $string, $match, $ids, $limit);
    }
    // If the view doesn't exist, we got FALSE, and fallback to the regular 'standard mode'.

    if ($references === FALSE) {
      $references = _game_clock_field_potential_references_standard($field, $string, $match, $ids, $limit);
    }

    // Store the results.
    $results[$cid] = $references;
  }

  return $results[$cid];
}

/**
 * Helper function for _game_clock_field_potential_references():
 * case of Views-defined referenceable nodes.
 */
function _game_clock_field_potential_references_views($field, $string = '', $match = 'contains', $ids = array(), $limit = NULL) {
  $view_name = $field['advanced_view'];

  if ($view = views_get_view($view_name)) {
    // We add a display, and let it derive from the 'default' display.
    // TODO: We should let the user pick a display in the fields settings - sort of requires AHAH...
    $display = $view->add_display('content_references');
    $view->set_display($display);

    // TODO from merlinofchaos on IRC : arguments using summary view can defeat the style setting.
    // We might also need to check if there's an argument, and set *its* style_plugin as well.
    $view->display_handler->set_option('style_plugin', 'content_php_array_autocomplete');
    $view->display_handler->set_option('row_plugin', 'fields');
    // Used in content_plugin_style_php_array::render(), to get
    // the 'field' to be used as title.
    $view->display_handler->set_option('content_title_field', 'title');

    // Additional options to let content_plugin_display_references::query()
    // narrow the results.
    $options = array(
      'table' => 'node',
      'field_string' => 'title',
      'string' => $string,
      'match' => $match,
      'field_id' => 'nid',
      'ids' => $ids,
    );
    $view->display_handler->set_option('content_options', $options);

    // TODO : for consistency, a fair amount of what's below
    // should be moved to content_plugin_display_references

    // Limit result set size.
    if (isset($limit)) {
      $view->display_handler->set_option('items_per_page', $limit);
    }

    // Get arguments for the view.
    if (!empty($field['advanced_view_args'])) {
      // TODO: Support Tokens using token.module ?
      $view_args = array_map('trim', explode(',', $field['advanced_view_args']));
    }
    else {
      $view_args = array();
    }

    // We do need title field, so add it if not present (unlikely, but...)
    $fields = $view->get_items('field', $display);
    if (!isset($fields['title'])) {
      $view->add_item($display, 'field', 'game_clocks', 'title');
    }

    // If not set, make all fields inline and define a separator.
    $options = $view->display_handler->get_option('row_options');
    if (empty($options['inline'])) {
      $options['inline'] = drupal_map_assoc(array_keys($view->get_items('field', $display)));
    }
    if (empty($options['separator'])) {
      $options['separator'] = '-';
    }
    $view->display_handler->set_option('row_options', $options);

    // Make sure the query is not cached
    $view->is_cacheable = FALSE;

    // Get the results.
    $result = $view->execute_display($display, $view_args);
  }
  else {
    $result = FALSE;
  }

  return $result;
}

/**
 * Helper function for _game_clock_field_potential_references():
 * referenceable nodes defined by content types.
 */
function _game_clock_field_potential_references_standard($field, $string = '', $match = 'contains', $ids = array(), $limit = NULL) {
  $related_types = array();
  $where = array();
  $args = array();

  if (is_array($field['referenceable_types'])) {
    foreach (array_filter($field['referenceable_types']) as $related_type) {
      $related_types[] = "c.type = '%s'";
      $args[] = $related_type;
    }
  }

  $where[] = implode(' OR ', $related_types);

  if (!count($related_types)) {
    return array();
  }

  if ($string !== '') {
    $match_operators = array(
      'contains' => "LIKE '%%%s%%'",
      'equals' => "= '%s'",
      'starts_with' => "LIKE '%s%%'",
    );
    $where[] = 'c.title '. (isset($match_operators[$match]) ? $match_operators[$match] : $match_operators['contains']);
    $args[] = $string;
  }
  elseif ($ids) {
    $where[] = 'c.cid IN (' . db_placeholders($ids) . ')';
    $args = array_merge($args, $ids);
  }

  $where_clause = $where ? 'WHERE ('. implode(') AND (', $where) .')' : '';
  $sql = "SELECT c.cid, c.title AS game_clock_title, c.type AS game_clock_type FROM {game_clocks} c $where_clause ORDER BY c.title, c.type";
  $result = $limit ? db_query_range($sql, $args, 0, $limit) : db_query($sql, $args);
  $references = array();
  while ($game_clock = db_fetch_object($result)) {
    $references[$game_clock->cid] = array(
      'title' => $game_clock->game_clock_title,
      'rendered' => $game_clock->game_clock_title,
    );
  }

  return $references;
}

/**
 * Menu callback; Retrieve a pipe delimited string of autocomplete suggestions for existing users
 */
function game_clock_field_autocomplete($field_name, $string = '') {
  $fields = content_fields();
  $field = $fields[$field_name];
  $match = isset($field['widget']['autocomplete_match']) ? $field['widget']['autocomplete_match'] : 'contains';
  $matches = array();

  $references = _game_clock_field_potential_references($field, $string, $match, array(), 10);
  foreach ($references as $id => $row) {
    // Add a class wrapper for a few required CSS overrides.
    $matches[$row['title'] ." [cid:$id]"] = '<div class="reference-autocomplete">'. $row['rendered'] . '</div>';
  }
  drupal_json($matches);
}

/**
 * Implementation of hook_node_types.
 */
// function game_clock_field_node_type($op, $info) {
//   switch ($op) {
//     case 'update':
//       // Reflect type name changes to the 'referenceable types' settings.
//       if (!empty($info->old_type) && $info->old_type != $info->type) {
//         // content.module's implementaion of hook_node_type() has already
//         // refreshed _content_type_info().
//         $fields = content_fields();
//         foreach ($fields as $field_name => $field) {
//           if ($field['type'] == 'game_clock_field' && isset($field['referenceable_types'][$info->old_type])) {
//             $field['referenceable_types'][$info->type] = empty($field['referenceable_types'][$info->old_type]) ? 0 : $info->type;
//             unset($field['referenceable_types'][$info->old_type]);
//             content_field_instance_update($field);
//           }
//         }
//       }
//       break;
//   }
// }

/**
 * Theme preprocess function.
 *
 * Allows specific node templates for nodes displayed as values of a
 * game_clock_field field with the 'full node' / 'teaser' formatters.
 */
function game_clock_field_preprocess_node(&$vars) {
  // The 'referencing_field' attribute of the node is added by the 'teaser'
  // and 'full node' formatters.
  if (!empty($vars['node']->referencing_field)) {
    $node = $vars['node'];
    $field = $node->referencing_field;
    $vars['template_files'][] = 'node-game_clock_field';
    $vars['template_files'][] = 'node-game_clock_field-'. $field['field_name'];
//     $vars['template_files'][] = 'node-game_clock_field-'. $node->type;
//     $vars['template_files'][] = 'node-game_clock_field-'. $field['field_name'] .'-'. $node->type;
  }
}

/**
 * FAPI theme for an individual elements.
 *
 * The textfield or select is already rendered by the
 * textfield or select themes and the html output
 * lives in $element['#children']. Override this theme to
 * make custom changes to the output.
 *
 * $element['#field_name'] contains the field name
 * $element['#delta]  is the position of this element in the group
 */
function theme_game_clock_field_select($element) {
  return $element['#children'];
}

function theme_game_clock_field_buttons($element) {
  return $element['#children'];
}

function theme_game_clock_field_autocomplete($element) {
  return $element['#children'];
}
